name: Open edX Product Proposal Submission
description: Choose this if you have an idea to propose, with a product proposal, for the Product Group to evaluate for potential addition to the Open edX Roadmap
title: "Put Initiative Name Here"
body:
  - type: markdown
    attributes:
      value: |
        ## Open edX Product Proposal Submission
        This template standardizes a method of representing all _**planned or proposed Initiatives, as well as current, in-flight Initiatives**_ that will be contributed to the Open edX Platform. It is intended to provide a high-level overview of the scope of the work, the approach, the value-add, and the anticipated impact. It should be written in such a way that a newcomer who may be unfamiliar with the Open edX platform can quickly gain an understanding of the “what”, the “why” and the “how” of the Initiative. See https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review for more detail.
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: Brief summary of the goal of the Initiative and the intended outcome. For example, if the Initiative is intended to fix a problem or pain point, include a problem statement and the proposed solution. If the Initiative is a new feature or an enhancement, include a statement about how the new feature will improve the platform, and for whom the improvements are intended.
    validations:
      required: true
  - type: input
    id: proplink
    attributes:
      label: Detailed Product Proposal
      description: Provide a link to your product proposal, if applicable
      placeholder: Link to public page on the Open edX wiki
  - type: textarea
    id: cb
    attributes:
      label: Context & Background (in brief, if a Product Proposal is linked above)
      description: Any relevant background information about the Initiative. What key pieces of information are important for newcomers to understand about the nature of the problem or pain point, the current user experience, etc.
    validations:
      required: true
  - type: textarea
    id: sa
    attributes:
      label: Scope & Approach (in brief, if a Product Proposal is linked above)
      description: Outline the scope of the Initiative and a description of how the work is being done. Who is the primary persona, ie the primary beneficiary of this Initiative? If appropriate, please provide links or a description of market research or user feedback/input that has shaped the Initiative. Please include links to design documentation that may be relevant. If the Initiative is in the early Discovery phase, please describe the Discovery method/hypothesis being tested.
    validations:
      required: true
  - type: textarea
    id: vi
    attributes:
      label: Value & Impact (in brief, if a Product Proposal is linked above)
      description: Please include the metrics being used to measure success for the Initiative. How will the Open edX platform and/or experience be measurably better than before?
    validations:
      required: true
  - type: textarea
    id: me
    attributes:
      label: Milestones and/or Epics
      description: |
        Any relevant background information about the Initiative. What key pieces of information are important for newcomers to understand about the nature of the problem or pain point, the current user experience, etc.  Please use the following format:

        **Milestone 1**: [Title]
        * [1-2 sentence abstract. Include key user stories if appropriate]
        * [Impact metric]
        * [Link to Epic where it may exist in GitHub]

        **Milestone 2**: etc...
    validations:
      required: true
  - type: input
    id: release
    attributes:
      label: Named Release
      description: First Named Release to include this initiative. Alphabetical named releases are generally cut in early April and early October. Based on the removal date, what named release would be the first without this code? Please reach out to the Build Test Release working group (#wg-build-test-release in Slack) if you're not sure. Use the letter, if you're not sure of the name.
      placeholder: Teak
    validations:
      required: true
  - type: textarea
    id: time
    attributes:
      label: Timeline (in brief, if a Product Proposal is linked above)
      description: Recognizing that many Initiatives evolve incrementally, please include a brief scope of the Initiative timeline. Please include a target Named Release, with contingencies if necessary.
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Proposed By
      description: Name of provider/organization
      placeholder: Axim
    validations:
      required: true
  - type: textarea
    id: addl
    attributes:
      label: Additional Info
      description: Links to external documents (for example, wiki pages, documents, or demos)
    validations:
      required: false
